### ISSUE TITLE
Robotics parts moving around/disappearing between scene loads

### ISSUE THREAD

**Issue by jakkarth** [sirkut/InfernalRobotics#17]
I'm sorry I can't be more specific. I'm trying to find a reproducible set of steps that make the issue occur. I've sent missions to duna and eve using IR hinges attached to long struts to use as adjustable landing gear, so that I can balance the ships if I land on uneven terrain. When I build in the VAB they're fine, when I launch them they're fine, but somewhere between my ejection burn and my insertion burn, something goes haywire. When switching back to a ship, I will find parts still connected to each other in terms of behavior, but far away from where they're supposed to be attached visually.

All of the interface controls operate as expected, as far as I can tell. The servo screen lists everything it's supposed to. The editor screen lets me move groups around. Using the servo screen to adjust the hinges has the correct effect when the hinges are still visible.

Here's a shot of a crane arm I built using rotatrons, hydraulic cylinders, and hinges. You can see they're floating in space, not attached to each other and the craft. 
![screenshot212](https://cloud.githubusercontent.com/assets/39682/3279915/29eab04a-f42b-11e3-892c-162d635c321a.png)

Here it is after I've rotated the Shoulder H hinge about 90 degrees. 
![screenshot213](https://cloud.githubusercontent.com/assets/39682/3279916/3cae7810-f42b-11e3-9222-1325564b9679.png)

Same thing from another angle:

![screenshot214](https://cloud.githubusercontent.com/assets/39682/3279917/4462b800-f42b-11e3-989e-30fd04f15593.png)
![screenshot215](https://cloud.githubusercontent.com/assets/39682/3279918/46da43be-f42b-11e3-83cf-d485be1f3d5d.png)

I've looked through the log, but the only IR-specific entries I see are "setupJoints - !gotOrig" and I do not understand what that means. Based on where it is in your code, it seems likely to have something to do with it, but I'm not very familiar with KSP modding so I'm not sure.

Please let me know what other information I could provide that would be of help. I can provide the craft file of the unbroken version of the ship pictured above, as well as the save file containing its current state, if that would help. I only see a way to attach images here, so I will have to post them somewhere else if you want them. Same for the KSP log file.

Thanks for making an awesome mod! Combined with KAS it truly revolutionizes the game and opens up a lot of cool possibilities!

**Comment by sirkut** [comment]
I would love a craft file so I can see what is going on.

Shawn

On Jun 14, 2014, at 9:23 PM, jakkarth notifications@github.com wrote:

I'm sorry I can't be more specific. I'm trying to find a reproducible set
of steps that make the issue occur. I've sent missions to duna and eve
using IR hinges attached to long struts to use as adjustable landing gear,
so that I can balance the ships if I land on uneven terrain. When I build
in the VAB they're fine, when I launch them they're fine, but somewhere
between my ejection burn and my insertion burn, something goes haywire.
When switching back to a ship, I will find parts still connected to each
other in terms of behavior, but far away from where they're supposed to be
attached visually.

All of the interface controls operate as expected, as far as I can tell.
The servo screen lists everything it's supposed to. The editor screen lets
me move groups around. Using the servo screen to adjust the hinges has the
correct effect when the hinges are still visible.

Here's a shot of a crane arm I built using rotatrons, hydraulic cylinders,
and hinges. You can see they're floating in space, not attached to each
other and the craft.
[image: screenshot212]
https://cloud.githubusercontent.com/assets/39682/3279915/29eab04a-f42b-11e3-892c-162d635c321a.png

Here it is after I've rotated the Shoulder H hinge about 90 degrees.
[image: screenshot213]
https://cloud.githubusercontent.com/assets/39682/3279916/3cae7810-f42b-11e3-9222-1325564b9679.png

Same thing from another angle:

[image: screenshot214]
https://cloud.githubusercontent.com/assets/39682/3279917/4462b800-f42b-11e3-989e-30fd04f15593.png
[image: screenshot215]
https://cloud.githubusercontent.com/assets/39682/3279918/46da43be-f42b-11e3-83cf-d485be1f3d5d.png

I've looked through the log, but the only IR-specific entries I see are
"setupJoints - !gotOrig" and I do not understand what that means. Based on
where it is in your code, it seems likely to have something to do with it,
but I'm not very familiar with KSP modding so I'm not sure.

Please let me know what other information I could provide that would be of
help. I can provide the craft file of the unbroken version of the ship
pictured above, as well as the save file containing its current state, if
that would help. I only see a way to attach images here, so I will have to
post them somewhere else if you want them. Same for the KSP log file.

Thanks for making an awesome mod! Combined with KAS it truly revolutionizes
the game and opens up a lot of cool possibilities!

—
Reply to this email directly or view it on GitHub
https://github.com/sirkut/InfernalRobotics/issues/17.

**Comment by jakkarth** [comment]
https://www.dropbox.com/s/5h5367jzmfqedmz/ir_bug.zip is a link to the files. I've included the craft file, a quicksave with the vessel loaded, and the full log file. Thanks for taking a look!

**Comment by sirkut** [comment]
Can I get a screenshot of your GameData directory so I can see which mods I
need to download to replicate it? I have a decent memory and I can spot
most of them but for a few parts I'm unsure of.

**Comment by sirkut** [comment]
Also, now that I think of it. Was this a craft you designed before
upgrading to the latest? ie. using 0.14?

**Comment by jakkarth** [comment]
GameData folder list (not all of these were used in the creation of the craft):

000_Toolbar
ActionGroupManager
AIES_Aerospace
AviationLights
B9_Aerospace
B9GearFix.cfg
BahaEPL
BahaSP
BetterRoveMates
BoulderCo
BrassMoustache
Chatterer
ConnectedLivingSpace
DistantObject
DMagic Orbital Science
EditorExtensions
EnvironmentalVisualEnhancements
ExsurgentEngineering
ExtraplanetaryLaunchpads
FinalFrontier.dat
Firespitter
FloorIt
FusTek
GNE
HabitatPack
HooliganLabs
HrmHaystack
HullCameraVDS
info.txt
KAS
KerbalJointReinforcement
Kethane
KineTechAnimation
KSPTweaks
KSPX
KWRocketry
LLL
MagicSmokeIndustries
MechJeb2
ModsByTal
ModularFuelTanks
ModuleManager.2.1.0.dll
NASAmission
NavyFish
NearFuture
Nereid
NothkeSerCom
NovaPunch2
potw
ProceduralDynamics
ProceduralFairings
RCSBuildAid
ReadMe-KerbalAlarmClock.txt
README.txt
RealChute
ResGen
SCANsat
SCANsatRPM
SelectRoot
ShipManifest
SimplePartOrganizer
SMP
SpaceplanePlus
Squad
SurfaceLights
SXT
TextureReplacer
ThrottleControlledAvionics
ThunderAerospace
toolbar-settings.dat
TriggerTech
UniverseReplacer
US_Core
US_KAS

For this craft, I believe it's limited to:

AviationLights
Firespitter
KAS
Kethane
LLL
MagicSmokeIndustries
MechJeb2
ModularFuelTanks
ModuleManager.2.1.0.dll
RealChute
SCANsat
Squad
SurfaceLights

It was designed either with 0.14b or 0.14d, not positive which. Running 0.14d now.

**Comment by jakkarth** [comment]
And by 0.14b and 0.14d, I mean 0.15b and 0.15d. Sorry. Never had 0.14 installed.

**Comment by sirkut** [comment]
I think there was a change on how the parts are attached which may explain
the weird distance issue. There isn't anything I can think of that will fix
it unfortunately.

**Comment by jakkarth** [comment]
Ok. I'm trying out a new craft built from scratch so I know for sure it's going to be 0.15d from the start. I'll post another comment here if I can reproduce it. Thanks for taking the time to look at it, and again for making an awesome mod!
