### ISSUE TITLE
SPH Right-clicking a mirrored part automatically overrides individual min/max settings

### ISSUE THREAD

**Issue by deckblad** [sirkut/InfernalRobotics#28]
In SPH or "mirrored" symmetry with one part mirrored to both sides, especially rotatrons. Set one side to "inverse" so they both move the same way. If you right-click a rotatron after setting unique min/max values via the main "grouping" GUI, the values of one immediately overwrite the min/max values on the other side.

I'm guessing the values on both refresh when the right-click GUI is drawn. I suggest not updating those values unless the UI sliders are moved

**Comment by sirkut** [comment]
Due to limitations of KSP and how symmetry mode is handled while in the VAB/SPH versus Flight I'm going to accept defeat and close this one. if you wish to store individual values across items that are placed symmetrically I suggest using a mod like PartWizard. http://forum.kerbalspaceprogram.com/threads/80124-0-23-5-Part-Wizard-(1-1-0)-6-Jun-2014
